# Generated by Django 3.0.3 on 2020-02-25 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200224_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ident',
            field=models.PositiveIntegerField(default=1234, help_text=' Pin to wartosc od 1 do 99999, będzie to twój pin do aplikacji', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Pin '),
        ),
    ]
