# Generated by Django 2.1.5 on 2020-02-05 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.BooleanField()),
                ('when_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('when_out', models.DateTimeField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Person')),
            ],
        ),
    ]
