# Generated by Django 3.0.3 on 2020-02-11 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Zalogowany',
                'verbose_name_plural': 'Zalogowani',
            },
        ),
        migrations.CreateModel(
            name='SignOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_out', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Wylogowany',
                'verbose_name_plural': 'Wylogowani',
            },
        ),
    ]
