# Generated by Django 2.1.5 on 2020-02-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='what',
            new_name='what_in',
        ),
    ]
