# Generated by Django 2.1.5 on 2020-02-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='when_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
