# Generated by Django 2.1.5 on 2020-02-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200205_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
