# Generated by Django 2.1.5 on 2020-02-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200205_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='when_out',
        ),
    ]
