# Generated by Django 2.1.5 on 2020-02-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_signin_when_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='what_in',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='when_in',
        ),
    ]
