# Generated by Django 2.1.5 on 2020-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20200205_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='do_you_in',
            field=models.BooleanField(default=True),
        ),
    ]
