# Generated by Django 2.1.5 on 2020-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_signin_do_you_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='do_you_out',
            field=models.BooleanField(default=True),
        ),
    ]
