# Generated by Django 2.1.5 on 2020-02-05 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_signin_do_you_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='when_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
