# Generated by Django 2.1.5 on 2020-02-05 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_signin_when_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='when_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
