# Generated by Django 2.1.5 on 2020-02-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_signin_when_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='do_you_in',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='do_you_out',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='when_out',
        ),
    ]
