# Generated by Django 2.1.5 on 2020-02-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_signout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signin',
            options={'verbose_name': 'Zalogowany', 'verbose_name_plural': 'Zalogowani'},
        ),
        migrations.AlterModelOptions(
            name='signout',
            options={'verbose_name': 'Wylogowany', 'verbose_name_plural': 'Wylogowani'},
        ),
    ]
