# Generated by Django 2.1.5 on 2020-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=40)),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('stake', models.FloatField(default=12)),
                ('own_passwd', models.IntegerField()),
            ],
        ),
    ]
