# Generated by Django 2.1.5 on 2020-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail '),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Imie '),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nazwisko '),
        ),
        migrations.AlterField(
            model_name='person',
            name='own_passwd',
            field=models.IntegerField(verbose_name='Kod użytkownika '),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=40, verbose_name='Stanowisko '),
        ),
        migrations.AlterField(
            model_name='person',
            name='stake',
            field=models.FloatField(blank=True, default=12, verbose_name='Stawka '),
        ),
    ]
