# Generated by Django 2.1.5 on 2020-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200206_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='stake',
            field=models.FloatField(blank=True, verbose_name='Stawka '),
        ),
    ]
