# Generated by Django 2.0.7 on 2020-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200205_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='stake',
            field=models.IntegerField(default=12),
        ),
    ]
