# Generated by Django 2.1.5 on 2020-02-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200206_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
    ]
