# Generated by Django 2.1.5 on 2020-02-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20200205_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='own_passwd',
            field=models.IntegerField(blank=True, default=1234),
        ),
    ]
