# Generated by Django 2.1.5 on 2020-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_person_own_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='own_passwd',
        ),
        migrations.AddField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='stake',
            field=models.FloatField(default=12),
        ),
    ]
