# Generated by Django 2.1.5 on 2020-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20200205_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='own_passwd',
            field=models.IntegerField(default=1234),
        ),
    ]
